# The URL the site will be built for
base_url = "https://zola-arabica.netlify.com"
generate_rss = true
compile_sass = false

title = "Zola Arabica"
description = "A minimal Zola theme"
highlight_code = true

# For other themes see:
# https://www.getzola.org/documentation/getting-started/configuration#syntax-highlighting
highlight_theme = "dimmed-fluid"

taxonomies = [
	{ name = "categories", paginate_by = 3, rss = true },
	{ name = "tags", paginate_by = 3 }
]

[extra]
author = "Michael Kuc"
menus = [ "about.md", "getting_started.md" ]
customJS = []
logoTitle = "Arabica"

postSummaryDateFormat = "%Y-%m"
postPageDateFormat = "%Y-%m-%d %H:%M"

#twitter = "Your Twitter username"
#facebook = "Your Facebook username"
