# The URL the site will be built for
base_url = "https://zola-arabica.netlify.com"
generate_rss = true
compile_sass = true

title = "Zola Arabica"
description = "A minimal Zola theme"
highlight_code = true

taxonomies = [
	{ name = "categories", paginate_by = 3, rss = true },
	{ name = "tags", paginate_by = 3 }
]

[extra]
author = "Michael Kuc"
menus = [ "about.md", "getting_started.md" ]
customJS = []
logoTitle = "Arabica"

postSummaryDateFormat = "%Y-%m"

#twitter = "Your Twitter username"
#facebook = "Your Facebook username"
