name = "Arabica"
license = "MIT"
licenselink = "https://github.com/nirocfz/arabica/blob/master/LICENSE"
description = "A port of the Ghost arabica theme for Hugo"
homepage = "https://github.com/nirocfz/arabica"
tags = ["blog", "minimal"]
features = ["smooth", "minimal"]
min_version = "0.41"

[author]
  name = "Michael Kuc"

# If porting an existing theme
[original]
  name = "Arabica"
  homepage = "https://arabica.netlify.app/"
  repo = "https://github.com/nirocfz/arabica"
